version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: is-postgres
    restart: always
    environment:
      POSTGRES_USER: invoicestudio
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: invoicestudio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
